"""Node / frontend artifacts.

`node_modules` is the flagship case: unambiguous, huge, and regenerated by one
command. Everything else in this ecosystem (`dist`, `build`, `coverage`) is
ambiguous and only becomes deletable when a Node project marker is proven
nearby.
"""

from __future__ import annotations

from dtcleaner.core.constants import Category, Ecosystem, RiskLevel
from dtcleaner.core.detectors.base import Rule, RuleDetector, register


class NodeDetector(RuleDetector):
    name = "node"
    ecosystem = Ecosystem.NODE
    rules = (
        Rule(
            name="node_modules",
            category=Category.NODE_MODULES,
            item_type="node_modules",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="npm install / pnpm install / yarn",
        ),
        Rule(
            name=".next",
            category=Category.FRONTEND_BUILD,
            item_type="next_build",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="next build",
        ),
        Rule(
            name=".nuxt",
            category=Category.FRONTEND_BUILD,
            item_type="nuxt_build",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="nuxt build",
        ),
        Rule(
            name=".turbo",
            category=Category.FRONTEND_BUILD,
            item_type="turbo_cache",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="turbo run build",
        ),
        Rule(
            name=".svelte-kit",
            category=Category.FRONTEND_BUILD,
            item_type="sveltekit_build",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="vite build",
        ),
        Rule(
            name=".parcel-cache",
            category=Category.FRONTEND_BUILD,
            item_type="parcel_cache",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="parcel build",
        ),
        Rule(
            name=".angular",
            category=Category.FRONTEND_BUILD,
            item_type="angular_cache",
            risk=RiskLevel.LOW,
            base_confidence=0.8,
            regenerate_hint="ng build",
        ),
        Rule(
            name=".vite",
            category=Category.FRONTEND_BUILD,
            item_type="vite_cache",
            risk=RiskLevel.LOW,
            base_confidence=0.75,
            regenerate_hint="vite build",
        ),
        # --- ambiguous names: require a proven Node project -----------------
        Rule(
            name="dist",
            category=Category.FRONTEND_BUILD,
            item_type="node_dist",
            risk=RiskLevel.LOW,
            base_confidence=0.5,
            regenerate_hint="npm run build",
        ),
        Rule(
            name="build",
            category=Category.FRONTEND_BUILD,
            item_type="node_build",
            risk=RiskLevel.LOW,
            base_confidence=0.5,
            regenerate_hint="npm run build",
        ),
        Rule(
            name="out",
            category=Category.FRONTEND_BUILD,
            item_type="node_out",
            risk=RiskLevel.MEDIUM,
            base_confidence=0.45,
            regenerate_hint="npm run build",
        ),
        Rule(
            name="coverage",
            category=Category.FRONTEND_BUILD,
            item_type="node_coverage",
            risk=RiskLevel.LOW,
            base_confidence=0.55,
            regenerate_hint="npm test -- --coverage",
        ),
        Rule(
            name="storybook-static",
            category=Category.FRONTEND_BUILD,
            item_type="storybook_static",
            risk=RiskLevel.LOW,
            base_confidence=0.7,
            regenerate_hint="npm run build-storybook",
        ),
    )


register(NodeDetector())
